# Dockerfile.react
FROM node:14

WORKDIR /app

COPY myapp/package.json .
COPY myapp/package-lock.json .

RUN npm install

COPY myapp/ .

RUN npm run build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]
