version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    # Removed volumes to prevent host-directory binding

  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    # Removed volumes to prevent host-directory binding
    depends_on:
      - fastapi
